#page title
page_title: PhotoCopyThis # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 123 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

url: # site url
privacy_policy_link: /privacy_policy.html
appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  https://yiningh.com
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/logo-1024.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: PhotoCopyThis # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Copy and share text from an image within a few clicks.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Yi-Ning Huang
your_link: https://yiningh.com
your_city:
email_address: support@photocopythis
facebook_username:
instagram_username:
twitter_username: photocopythis
github_username:
youtube_username:

# Feature List
features:
  - title: Copy and Share text from an Image
    description: Copy and Share text from an image by taking a photo or choosing photo from your album
    fontawesome_icon_name: copy

  - title: Automatic language detection
    description: Support 60 languages and detect languages automatically
    fontawesome_icon_name: language

  - title: Integrate with Siri Shortcuts
    description: Quickly launch the app with Siri Shortcuts
    fontawesome_icon_name: fighter-jet

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage2.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#fff"

link_color: "#ffcc66"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#E56530"
feature_text_color: "#666666"
text_color: "#666"
title_color: "#666666"

feature_icons_foreground_color: "#E56530"
feature_icons_background_color: "#FAEDEE"

social_icons_foreground_color: "#E56530"
social_icons_background_color: "#FAEDEE"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
